-- Rustex reference schema (PostgreSQL 16)
--
-- This file is a human-readable reference for the domain model. The
-- authoritative, versioned schema is generated by EF Core migrations from
-- server/src/Rustex.Domain/Entities — run:
--   dotnet ef migrations add InitialCreate -p server/src/Rustex.Infrastructure -s server/src/Rustex.Api
-- to produce the real migration. Keep this file in sync manually when the
-- entity model changes; it is documentation, not what gets applied.

create extension if not exists pgcrypto;

-- ============================================================
-- Identity
-- ============================================================

create table users (
    id                uuid primary key default gen_random_uuid(),
    discord_id        varchar(32) not null unique,
    discord_username  varchar(64) not null,
    discord_avatar    varchar(256),
    email             varchar(256),
    is_active         boolean not null default true,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now(),
    last_login_at     timestamptz
);

create table user_profiles (
    user_id       uuid primary key references users(id) on delete cascade,
    display_name  varchar(64),
    bio           varchar(500),
    timezone      varchar(64) not null default 'UTC',
    locale        varchar(16) not null default 'en-US',
    avatar_url    varchar(512)
);

create table user_settings (
    user_id             uuid primary key references users(id) on delete cascade,
    theme               varchar(32) not null default 'tactical-dark',
    sound_enabled       boolean not null default true,
    desktop_enabled     boolean not null default true,
    browser_enabled     boolean not null default true,
    discord_enabled     boolean not null default false,
    push_enabled        boolean not null default false,
    call_enabled        boolean not null default false,
    quiet_hours_start   time,
    quiet_hours_end     time,
    quiet_hours_tz      varchar(64) not null default 'UTC',
    mute_schedule       jsonb not null default '{}'::jsonb,
    updated_at          timestamptz not null default now()
);

create table sessions (
    id                  uuid primary key default gen_random_uuid(),
    user_id             uuid not null references users(id) on delete cascade,
    refresh_token_hash  varchar(256) not null unique,
    user_agent          varchar(256),
    ip_address          varchar(64),
    created_at          timestamptz not null default now(),
    expires_at          timestamptz not null,
    revoked_at          timestamptz
);
create index idx_sessions_user on sessions(user_id);

-- ============================================================
-- Teams / roles / permissions
-- ============================================================

create table teams (
    id          uuid primary key default gen_random_uuid(),
    name        varchar(64) not null,
    slug        varchar(64) not null unique,
    owner_id    uuid not null references users(id),
    icon_url    varchar(512),
    created_at  timestamptz not null default now()
);

create table permissions (
    id           uuid primary key default gen_random_uuid(),
    key          varchar(64) not null unique,   -- e.g. "servers.manage", "alerts.acknowledge"
    description  varchar(256)
);

create table team_roles (
    id        uuid primary key default gen_random_uuid(),
    team_id   uuid not null references teams(id) on delete cascade,
    name      varchar(32) not null,             -- Owner / Admin / Member / custom
    is_system boolean not null default false,
    unique(team_id, name)
);

create table team_role_permissions (
    team_role_id   uuid not null references team_roles(id) on delete cascade,
    permission_id  uuid not null references permissions(id) on delete cascade,
    primary key (team_role_id, permission_id)
);

create table team_members (
    id         uuid primary key default gen_random_uuid(),
    team_id    uuid not null references teams(id) on delete cascade,
    user_id    uuid not null references users(id) on delete cascade,
    role_id    uuid not null references team_roles(id),
    status     varchar(16) not null default 'active', -- active | invited | removed
    joined_at  timestamptz not null default now(),
    unique(team_id, user_id)
);

create table team_invites (
    id                uuid primary key default gen_random_uuid(),
    team_id           uuid not null references teams(id) on delete cascade,
    inviter_id        uuid not null references users(id),
    invitee_discord   varchar(64),
    token             varchar(128) not null unique,
    status            varchar(16) not null default 'pending', -- pending | accepted | expired | revoked
    expires_at        timestamptz not null,
    created_at        timestamptz not null default now()
);

-- ============================================================
-- Servers
-- ============================================================

create table rust_servers (
    id                uuid primary key default gen_random_uuid(),
    team_id           uuid references teams(id) on delete cascade,
    owner_user_id     uuid not null references users(id),
    name              varchar(64) not null,
    ip_address        varchar(64) not null,
    game_port         integer not null,
    query_port        integer,
    map_name          varchar(64),
    seed              bigint,
    world_size        integer,
    description       varchar(500),
    status            varchar(16) not null default 'unknown', -- online | offline | unknown
    tags              text[] not null default '{}',
    is_favorite        boolean not null default false,
    wipe_schedule     varchar(128),
    restart_schedule  varchar(128),
    auto_reconnect    boolean not null default true,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);
create index idx_rust_servers_team on rust_servers(team_id);
create index idx_rust_servers_owner on rust_servers(owner_user_id);

create table server_status_snapshots (
    id            uuid primary key default gen_random_uuid(),
    server_id     uuid not null references rust_servers(id) on delete cascade,
    ping_ms       integer,
    player_count  integer,
    max_players   integer,
    queue_size    integer,
    recorded_at   timestamptz not null default now()
);
create index idx_server_status_server_time on server_status_snapshots(server_id, recorded_at desc);

-- ============================================================
-- Raid events
-- ============================================================

create table raid_events (
    id                uuid primary key default gen_random_uuid(),
    server_id         uuid not null references rust_servers(id) on delete cascade,
    detected_at       timestamptz not null default now(),
    grid              varchar(8),
    map_x             double precision,
    map_y             double precision,
    tier              varchar(8) not null default 'Tier1', -- Tier1 | Tier2 | Tier3 — count-based, see raid_alarm_settings
    raid_type         varchar(32),                         -- rocket | c4 | satchel | mlrs | mixed ...
    explosion_count   integer not null default 0,
    estimated_size    varchar(16),                          -- solo | duo | small_team | large_team
    status            varchar(16) not null default 'active', -- active | quiet | ended
    source            varchar(32) not null default 'simulated', -- simulated | rustplus | plugin
    metadata          jsonb not null default '{}'::jsonb,
    ended_at          timestamptz
);
create index idx_raid_events_server_time on raid_events(server_id, detected_at desc);

-- Per-server raid-alarm configuration. Defaults match the "1 explosion = Tier 1, 3 = Tier 2,
-- 5 = Tier 3" classification — see Rustex.Domain.RaidAlarm.RaidAlarmEvaluator.
create table raid_alarm_settings (
    id                  uuid primary key default gen_random_uuid(),
    server_id           uuid not null unique references rust_servers(id) on delete cascade,
    is_enabled          boolean not null default true,
    tier1_threshold     integer not null default 1,
    tier2_threshold     integer not null default 3,
    tier3_threshold     integer not null default 5,
    time_window_seconds integer not null default 30,
    cluster_radius      double precision not null default 50,
    cooldown_seconds    integer not null default 120,
    updated_at          timestamptz not null default now()
);

-- ============================================================
-- Notifications
-- ============================================================

create table notifications (
    id                  uuid primary key default gen_random_uuid(),
    user_id             uuid not null references users(id) on delete cascade,
    type                varchar(32) not null,
    title               varchar(128) not null,
    body                varchar(500),
    severity            varchar(16) not null default 'info',
    is_read             boolean not null default false,
    related_entity_type varchar(32),
    related_entity_id   uuid,
    created_at          timestamptz not null default now()
);
create index idx_notifications_user on notifications(user_id, created_at desc);

create table notification_history (
    id               uuid primary key default gen_random_uuid(),
    notification_id  uuid not null references notifications(id) on delete cascade,
    channel          varchar(16) not null, -- inapp | desktop | browser | discord | push | call
    status           varchar(16) not null, -- queued | sent | delivered | failed
    sent_at          timestamptz,
    delivered_at     timestamptz,
    error            varchar(500)
);

create table webhooks (
    id          uuid primary key default gen_random_uuid(),
    team_id     uuid references teams(id) on delete cascade,
    server_id   uuid references rust_servers(id) on delete cascade,
    url         varchar(512) not null,
    secret      varchar(256) not null,
    event_types text[] not null default '{}',
    is_active   boolean not null default true,
    created_at  timestamptz not null default now()
);

-- ============================================================
-- Maps / markers
-- ============================================================

create table maps (
    id              uuid primary key default gen_random_uuid(),
    server_id       uuid not null references rust_servers(id) on delete cascade,
    image_url       varchar(512),
    width           integer,
    height          integer,
    monument_data   jsonb not null default '[]'::jsonb,
    updated_at      timestamptz not null default now()
);

create table markers (
    id              uuid primary key default gen_random_uuid(),
    map_id          uuid not null references maps(id) on delete cascade,
    created_by      uuid not null references users(id),
    type            varchar(32) not null, -- raid | team | player | custom | monument
    x               double precision not null,
    y               double precision not null,
    label           varchar(128),
    color           varchar(16),
    is_shared       boolean not null default true,
    created_at      timestamptz not null default now()
);

-- ============================================================
-- Team chat automation
-- ============================================================

create table team_messages (
    id          uuid primary key default gen_random_uuid(),
    team_id     uuid not null references teams(id) on delete cascade,
    user_id     uuid references users(id),
    content     varchar(1000) not null,
    created_at  timestamptz not null default now()
);

create table message_templates (
    id                uuid primary key default gen_random_uuid(),
    team_id           uuid not null references teams(id) on delete cascade,
    server_id         uuid references rust_servers(id) on delete cascade,
    event_type        varchar(64) not null, -- RaidDetected | RocketFired | CargoShip | ...
    template_text     varchar(500) not null,
    is_enabled        boolean not null default true,
    cooldown_seconds  integer not null default 30,
    created_at        timestamptz not null default now(),
    unique(team_id, server_id, event_type)
);

-- ============================================================
-- Logs / analytics
-- ============================================================

create table audit_logs (
    id           uuid primary key default gen_random_uuid(),
    user_id      uuid references users(id),
    team_id      uuid references teams(id),
    action       varchar(64) not null,
    entity_type  varchar(32),
    entity_id    uuid,
    metadata     jsonb not null default '{}'::jsonb,
    created_at   timestamptz not null default now()
);
create index idx_audit_logs_team_time on audit_logs(team_id, created_at desc);

create table analytics_snapshots (
    id                uuid primary key default gen_random_uuid(),
    server_id         uuid not null references rust_servers(id) on delete cascade,
    period_start      timestamptz not null,
    period_end        timestamptz not null,
    raid_count        integer not null default 0,
    peak_hour_utc     integer,
    avg_ping_ms       integer,
    player_activity   jsonb not null default '{}'::jsonb,
    created_at        timestamptz not null default now()
);

-- ============================================================
-- Emergency phone call system
-- ============================================================

create table phone_numbers (
    id                        uuid primary key default gen_random_uuid(),
    user_id                   uuid not null references users(id) on delete cascade,
    e164_number_encrypted     varchar(512) not null, -- encrypted at rest, decrypted only in Infrastructure
    label                     varchar(64),
    is_primary                boolean not null default false,
    is_verified               boolean not null default false,
    is_call_enabled           boolean not null default true,
    verification_code_hash    varchar(256),
    verification_expires_at   timestamptz,
    created_at                timestamptz not null default now()
);
create index idx_phone_numbers_user on phone_numbers(user_id);

create table call_alert_settings (
    id                     uuid primary key default gen_random_uuid(),
    user_id                uuid not null references users(id) on delete cascade,
    server_id              uuid references rust_servers(id) on delete cascade, -- null = applies to all servers
    trigger_type           varchar(64) not null, -- RaidDetected | LargeRaid | SustainedExplosions | ...
    is_enabled             boolean not null default true,
    min_tier                varchar(8) not null default 'Tier2',
    min_explosion_count     integer not null default 3,
    cooldown_seconds        integer not null default 300,
    created_at              timestamptz not null default now(),
    unique(user_id, server_id, trigger_type)
);

create table call_alerts (
    id                uuid primary key default gen_random_uuid(),
    user_id           uuid not null references users(id) on delete cascade,
    server_id         uuid not null references rust_servers(id) on delete cascade,
    raid_event_id     uuid references raid_events(id) on delete set null,
    phone_number_id   uuid not null references phone_numbers(id),
    provider          varchar(16) not null, -- twilio | vonage | plivo
    status            varchar(16) not null default 'queued', -- queued | ringing | answered | missed | failed
    duration_seconds  integer,
    retry_count       integer not null default 0,
    acknowledged      boolean not null default false,
    initiated_at      timestamptz not null default now(),
    answered_at       timestamptz,
    ended_at          timestamptz,
    error             varchar(500)
);
create index idx_call_alerts_user_time on call_alerts(user_id, initiated_at desc);
